services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 1234:5432
    volumes:
      - pg:/var/lib/postgresql/data
    env_file:
      - back-end/.env

  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - back-end/.env

  react_app:
    container_name: react_app
    build: ./front-end
    volumes:
      - volumes_react:/var/www/html

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - volumes_react:/var/www/html
    depends_on:
      - db
      - node_app
      - react_app

volumes:
  pg:
  volumes_react:
