services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 1234:5432
    volumes:
      - pg:/var/lib/postgresql/data
    env_file:
      - .env

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
volumes:
  pg: