name: Deploy on AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make back-end envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: ${{secrets.DB_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.DB}}
          envkey_DATABASE_URL: ${{secrets.DB_URL}}
          directory: back-end/
          file_name: .env
          fail_on_empty: true
      - name: Make front-end envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_BASE_URL: ${{secrets.REACT_URL}}
          directory: front-end/
          file_name: .env
          fail_on_empty: true
      - name: build
        run: docker-compose build
      - name: run
        run: docker-compose down && docker-compose up -d
